version: "3.3"
services:
  redis:
    image: "redis"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  webapp:
    build: .
    ports:
      - "5000:80"
    environment:
      APP_USER: Name

volumes:
  redis_data:
